# Generated by Django 4.0.6 on 2022-07-19 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nsapp', '0002_remove_project_user_user_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_to', to='nsapp.project')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
